apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-vwk4po
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vwk4po
  namespace: my-nginx-vwk4po
  labels:
    name: nginx-vwk4po
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-vwk4po
  template:
    metadata:
      namespace: my-nginx-vwk4po
      labels:
        name: nginx-vwk4po
    spec:
      containers:
      - name: nginx-vwk4po
        image: nginx
        ports:
        - containerPort: 80

